### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by mocking3** [globocom/kong-plugin-proxy-cache#1]
when response code is 404

log error :attempt to set ngx.header.HEADER after sending out response headers while sending to client

**Comment by patrickporto** [comment]
Hi @mocking3

We need to more details 😕. What plugin version, kong version and openresty version you are using?

Can you improve the issue title? Please 😄

**Comment by patrickporto** [comment]
A bug was fixed. The `X-Cache-Status` must not be defined in `body_filter` context.

Please, upgrade the plugin version 😄 

https://github.com/openresty/lua-nginx-module/issues/825
