### ISSUE TITLE
X-Cache-Status is always MISS 

### ISSUE THREAD

**Issue by zhn1010** [globocom/kong-plugin-proxy-cache#5]
I have a service in Kong and I have set proxy-cache plugin for that service.

`curl -X POST http://localhost:8001/plugins --data "name=proxy-cache" --data 'service_id=2f0a285d-7b25-48d6-adc3-bbf28ffe5f47' --data "config.redis.host=127.0.0.1" --data "config.redis.port=6379" --data "config.redis.password=my_redis_password"`

When I call an API from that service:

`curl -i -X GET --url http://localhost:3002/v1/currency --header 'apikey: MY_API_KEY'`

 everything works correctly but **X-Cache-Status** is always **MISS**

`
HTTP/1.1 200 OK                                                                                                                                       Content-Type: application/json; charset=utf-8                                                                                                         Content-Length: 3654                                                                                                                                  Connection: keep-alive                                                                                                                                X-Cache-Status: MISS                                                                                                                                  X-RateLimit-Limit-second: 100                                                                                                                         X-RateLimit-Remaining-second: 99                                                                                                                      X-Powered-By: Express                                                                                                                                 Access-Control-Allow-Origin: *
...
`
How can I debug Miss reason?

**Comment by patrickporto** [comment]
Hi @zhn1010 

This plugin is an open source alternative to [proxy-cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) of Kong Enterprise.

You are probably using the Kong Enterprise plugin

**Comment by zhn1010** [comment]
> Hi @zhn1010
> 
> This plugin is an open source alternative to [proxy-cache](https://docs.konghq.com/hub/kong-inc/proxy-cache/) of Kong Enterprise.
> 
> You are probably using the Kong Enterprise plugin

You are right. Now I use this open source plugin and I always get **Miss** for **X-Cache-Status** .

**Comment by patrickporto** [comment]
Can you verify the `cache_control` config? If the upstream has not `Cache-Control` header in response so `cache_control` should be `false` and the cache TTL is `cache_ttl` instead of `max-age`

**Comment by raselSoftNode** [comment]
@patrickporto can you check my problem . in my case X-Cache-Status always "Bypass".

this is my server =>
```js
const express=require("express")
const cors=require("cors")

const app=express()

app.get("/echo",(req,res)=>{
    res.setHeader('Cache-Control', 'max-age=300'); 

    res.status(200).json({name:"rasel",age:25,sub:["bangla","english"]})
})

app.get("/remote",(req,res)=>{
    res.setHeader('Cache-Control', 'max-age=300'); 

    res.status(200).json({name:"this is remote server"})
})

app.listen(4000,()=>{
    console.log("http://localhost:4000")
})
```


And this is my kong.yml file => 
```js
_format_version: "2.1"


services:
  - name: echo-server
    host: host.docker.internal
    port: 4000
    path: /echo
    routes:
      - name: localhost_echo_route
        paths:
        - /echo_server
        - /echo_server2
  - name: remote_server
    host: host.docker.internal
    port: 4000
    path: /remote
    routes:
     - name: localhost_remote_routee
       paths:
        - /remote_server
        - /remote_server2

# plugins
plugins:
- name: proxy-cache
  config:
    response_code:
    - 200
    request_method:
    - GET
    - HEAD
    content_type:
    - text/plain
    - application/json
    cache_ttl: 300
    strategy: memory
    cache_control: false

```

My Browser Response => 
![image](https://github.com/globocom/kong-plugin-proxy-cache/assets/126503071/59c4e762-0d98-467d-9257-009b3a1f1f0b)
