### ISSUE TITLE
How to install on a Kong Kubernetes cluster?

### ISSUE THREAD

**Issue by holidaycottages** [globocom/kong-plugin-proxy-cache#6]
I have a cluster of Kong running.

How does one go about getting your plugin there?

**Comment by patrickporto** [comment]
Hi @holidaycottages 

You can install following the [README](https://github.com/globocom/kong-plugin-proxy-cache#installing). So you can enable following the [kong documentation](https://docs.konghq.com/1.1.x/plugin-development/distribution/#load-the-plugin).

**Comment by holidaycottages** [comment]
Thanks for that.

Already read all of that, but I still am unsure how to connect luarocks to my K8 cluster? Changing the config is simple
